### ISSUE TITLE
setPreference() 

### ISSUE THREAD

**Issue by appache7-2** [samaybhavsar/google-scraper#2]
Can you tell me more about function setPreference( )
I would like to pass results over a defined period.

Thx

**Comment by samaybhavsar** [comment]
Thats a great idea. I have not included the extra filters which Google Search provides but can surely be added on to it.

**Comment by appache7-2** [comment]
I think it should look something like this, but I'm not there yet.
Nice that you're still alive .. xD nice to meet you !

for ...
`$data=$this->getpagedata('http://www.google.fr/search?q='.$this->keyword.'&num=100&tbs=cdr:1,cd_min:1/1/2000,cd_max:1/1/2009,ctr:countryFR&source=lnt&cr=countryFR&ei='.$this->ei.'&start='.$i.'&sa=N&biw=1920&bih=949');`

**Comment by samaybhavsar** [comment]
Why don't you try updating it and send me a pull request. I will merge it. Nice to meeting you.

**Comment by appache7-2** [comment]
I'm not sure it works, I have trouble finding the same result from my own google results and those of the script, I do not have the same links.
