### ISSUE TITLE
Difference in hidden 'sig' input.

### ISSUE THREAD

**Issue by haldir** [samaybhavsar/google-scraper#3]
This line (in setPreference):
`preg_match('/<input type="hidden" name="sig" value="(.*?)">/', $data, $matches);`
didn't get any values, so I found the name and type were written after the value in the preferences page of google.
So this line:
`preg_match('/<input value="(.*?)" name="sig" type="hidden">/', $data, $matches);`
got the correct result.

I'm not sure if this is only for me, or if in fact google changed the input.

**Comment by samaybhavsar** [comment]
Fixed this.
